### ISSUE TITLE
convert phytest to plugin

### ISSUE THREAD

**Issue by Wytamma** [phytest-devs/phytest#17]
The way we have written phytest means that it works as a plugin. For example phytest can be registered as a pytest plugin:

```bash
pytest tests.py -p phytest -D data/ebola_metadata.csv -A data/ebola.fasta -T data/ebola.fasta.treefile
```

Should we just add the [entry point](https://docs.pytest.org/en/7.1.x/how-to/writing_plugins.html#setuptools-entry-points) so that when phytest is installed it works with pytest without having to use the `-p` flag?

**Comment by rbturnbull** [comment]
I added the required stuff to pyproject.toml and added 'Framework :: Pytest' to the classifiers so that phytest comes up in as a pytest plugin.

When you run the ebola example in phytest-continuous-testing-example it now runs with:
`pytest tests.py -D data/ebola_metadata.csv -A data/ebola.fasta -T data/ebola.fasta.treefile`
